spring: 
  profiles: 
    active: 
    - test
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: '{cipher}003609124eda020f616bf3175a8e24e48252926053c3d0b524d650b84eee51397b745b45f7c7323f56d8630aa2b74024'
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dv.com:7001/eureka/new
--- 
server: 
  port: 8202
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/